## Try PCA from scratch - 6 lines of code - extra points, else scikit package can be used -> no extra points!!

In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages (from pandas) (2.9.0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 33.9 MB/s eta 0:00:00 0:00:01
Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 32.7 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.1 pandas-2.2.2 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
df=pd.read_csv("/Users/ananyaagrawal/Desktop/CMU Sem 1/38615-Computational Modelling-ML for Science/Assignment/hw1_dataset.csv")

In [3]:
df

,experimental_proprty,MS_enc,nHetero,nX,C2SP3,MPC5,ATS0i,NaasN,SsCH3,nCl,...,AATS0Z,ATSC0are,ATSC2pe,SsCl,ATS6v,AATSC1dv,nFARing,AATS2v,Xp-7dv,n6Ring
0,3.54,PPENPINEAPLE42,5,1,0,83,7305.483137,1,2.105782,1,...,26.444444,2.995920,-0.508149,5.976320,16177.071020,1.102539,0,223.767000,0.903808,3
1,-1.18,PPENPINEAPLE42,11,0,3,114,9532.633527,0,4.605907,0,...,31.796610,9.996180,2.554415,0.000000,29893.511410,0.854039,1,225.916087,1.887922,3
2,3.69,PPENPINEAPLE42,5,1,2,69,5845.023999,0,1.422763,1,...,35.513514,3.773573,-0.113725,6.285975,17264.331087,0.793417,1,241.492298,1.098203,2
3,3.37,HTXPTDWTTWOBJR,9,1,3,105,7388.625069,0,0.000000,1,...,35.869565,6.699887,-0.114253,5.958016,20506.327989,0.421656,1,254.318903,1.164550,2
4,3.10,PPENPINEAPLE42,7,0,2,68,9082.560968,1,9.734779,0,...,21.018182,5.862455,1.664804,0.000000,22748.101433,1.602810,0,207.685522,0.492884,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2.06,PPENPINEAPLE42,12,2,5,111,11428.201740,0,0.000000,0,...,24.970588,12.971651,-0.366319,0.000000,24723.464405,1.033473,0,222.862881,0.893994,3
1996,3.03,PPENPINEAPLE42,6,2,2,66,7372.541891,0,0.000000,1,...,28.888889,7.099480,-0.890364,5.860789,14440.287915,0.773582,0,225.391710,0.728822,3
1997,3.80,VMZXVMIGMRZLPU,9,0,0,74,9326.669184,0,7.191590,0,...,22.285714,8.026598,1.374708,0.000000,19394.335824,1.780040,0,197.446318,0.562785,3
1998,3.22,HTXPTDWTTWOBJR,9,1,2,103,6732.866534,0,0.000000,1,...,38.000000,5.735850,1.192770,5.946582,17791.951828,0.622862,1,265.517011,1.081912,2
1999,1.75,PPENPINEAPLE42,7,1,0,86,8308.409901,0,7.529184,0,...,22.960000,7.908792,0.911598,0.000000,19535.696503,1.641015,1,221.023164,0.651765,1

In [6]:
df.describe()

,experimental_proprty,nHetero,nX,C2SP3,MPC5,ATS0i,NaasN,SsCH3,nCl,nFAHRing,...,AATS0Z,ATSC0are,ATSC2pe,SsCl,ATS6v,AATSC1dv,nFARing,AATS2v,Xp-7dv,n6Ring
count,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,2.170570,7.16850,0.777000,2.197000,87.181500,7900.675402,0.320000,2.492567,0.310500,0.138000,...,28.296718,6.595132,1.213197,1.881112,19740.449279,0.992060,0.180000,232.421533,0.940024,2.739000
std,1.207616,2.80536,1.131774,2.464595,32.645987,2509.808249,0.608099,2.618002,0.611782,0.361969,...,11.856430,3.401378,2.132366,3.702866,9646.734706,0.433694,0.405811,23.426851,0.551662,1.154793
min,-1.500000,1.00000,0.000000,0.000000,5.000000,2046.021324,0.000000,0.000000,0.000000,0.000000,...,13.963636,1.004362,-2.651889,0.000000,0.000000,-1.733701,0.000000,146.574278,0.000000,0.000000
25%,1.370000,5.00000,0.000000,0.000000,65.000000,6079.002988,0.000000,0.000000,0.000000,0.000000,...,23.134685,4.195381,0.000105,0.000000,13383.088573,0.725016,0.000000,217.249400,0.534909,2.000000
50%,2.340000,7.00000,0.000000,2.000000,87.000000,7936.233818,0.000000,1.892550,0.000000,0.000000,...,26.356349,6.118333,0.737282,0.000000,19802.731197,1.013047,0.000000,229.015392,0.860695,3.000000
75%,3.100000,9.00000,1.000000,3.000000,107.000000,9583.208572,1.000000,3.800859,0.000000,0.000000,...,30.678796,8.080698,1.608892,0.000000,25180.554961,1.275830,0.000000,246.158979,1.222062,3.000000
max,4.500000,34.00000,9.000000,27.000000,269.000000,34080.577108,4.000000,23.704286,3.000000,2.000000,...,336.666667,30.660088,14.070111,18.485023,118642.819179,2.423830,2.000000,341.676240,4.276742,8.000000