In [2]:
# import required libraries
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [3]:
# read dataset csv
hw = pd.read_csv('hw1_dataset.csv')
hw

,experimental_proprty,MS_enc,nHetero,nX,C2SP3,MPC5,ATS0i,NaasN,SsCH3,nCl,...,AATS0Z,ATSC0are,ATSC2pe,SsCl,ATS6v,AATSC1dv,nFARing,AATS2v,Xp-7dv,n6Ring
0,3.54,PPENPINEAPLE42,5,1,0,83,7305.483137,1,2.105782,1,...,26.444444,2.995920,-0.508149,5.976320,16177.071020,1.102539,0,223.767000,0.903808,3
1,-1.18,PPENPINEAPLE42,11,0,3,114,9532.633527,0,4.605907,0,...,31.796610,9.996180,2.554415,0.000000,29893.511410,0.854039,1,225.916087,1.887922,3
2,3.69,PPENPINEAPLE42,5,1,2,69,5845.023999,0,1.422763,1,...,35.513514,3.773573,-0.113725,6.285975,17264.331087,0.793417,1,241.492298,1.098203,2
3,3.37,HTXPTDWTTWOBJR,9,1,3,105,7388.625069,0,0.000000,1,...,35.869565,6.699887,-0.114253,5.958016,20506.327989,0.421656,1,254.318903,1.164550,2
4,3.10,PPENPINEAPLE42,7,0,2,68,9082.560968,1,9.734779,0,...,21.018182,5.862455,1.664804,0.000000,22748.101433,1.602810,0,207.685522,0.492884,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2.06,PPENPINEAPLE42,12,2,5,111,11428.201740,0,0.000000,0,...,24.970588,12.971651,-0.366319,0.000000,24723.464405,1.033473,0,222.862881,0.893994,3
1996,3.03,PPENPINEAPLE42,6,2,2,66,7372.541891,0,0.000000,1,...,28.888889,7.099480,-0.890364,5.860789,14440.287915,0.773582,0,225.391710,0.728822,3
1997,3.80,VMZXVMIGMRZLPU,9,0,0,74,9326.669184,0,7.191590,0,...,22.285714,8.026598,1.374708,0.000000,19394.335824,1.780040,0,197.446318,0.562785,3
1998,3.22,HTXPTDWTTWOBJR,9,1,2,103,6732.866534,0,0.000000,1,...,38.000000,5.735850,1.192770,5.946582,17791.951828,0.622862,1,265.517011,1.081912,2
1999,1.75,PPENPINEAPLE42,7,1,0,86,8308.409901,0,7.529184,0,...,22.960000,7.908792,0.911598,0.000000,19535.696503,1.641015,1,221.023164,0.651765,1

In [10]:
# X = features, Y = target
# features in X are contributing in some manner to result in the Y value
data_X = hw.iloc[:,1:]
data_Y = hw.iloc[:, 0]
data_X
data_Y

0       3.54
1      -1.18
2       3.69
3       3.37
4       3.10
        ...
1995    2.06
1996    3.03
1997    3.80
1998    3.22
1999    1.75
Name: experimental_proprty, Length: 2000, dtype: float64

In [5]:
# the dataset has columns that contain string values, we only filter out the numerical columns
# also remove any rows that might have null or NA values
cleaned_X = data_X.select_dtypes(include=['int64', 'float64']).dropna()

# modify Y to remove rows that were removed from X
cleaned_Y = data_Y.loc[cleaned_X.index].reset_index(drop=True)
cleaned_X = cleaned_X.reset_index(drop=True)

In [6]:
PCA_COMPONENTS = 50

In [7]:
# standardize the features (important for PCA)
scaler = StandardScaler()
scaled_X = scaler.fit_transform(cleaned_X)

# initialize PCA with components count
pca = PCA(n_components=PCA_COMPONENTS)

# fit PCA on the scaled data and transform X
pca_X = pca.fit_transform(scaled_X)

# create a df for the PCA results
df_pca_X = pd.DataFrame(pca_X, columns=[f'PC{i+1}' for i in range(PCA_COMPONENTS)])

# concatenate the PCA results with the target column from Y
final_df = pd.concat([df_pca_X, cleaned_Y.reset_index(drop=True)], axis=1)
print(final_df)
explained_variance = pca.explained_variance_ratio_
print(f'Explained variance by each component: {explained_variance}')

            PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0     -4.643026 -4.764737 -5.442995  0.473139 -0.936514  5.302679 -3.903191
1     13.772560  2.858812  5.632351  2.840135  4.086337 -0.410647 -0.709477
2     -9.037657 -0.384474  0.285757  2.692442  4.420641  3.823686 -2.142428
3      2.346726  6.464077  0.890574  1.058670  3.842966  2.574841  0.837360
4      1.406361 -5.656511  3.566759 -4.551216  0.150934 -2.339288  1.729947
...         ...       ...       ...       ...       ...       ...       ...
1895  16.152261  2.192617 -1.235029 -1.120326 -8.254566  1.630798  1.870973
1896  -5.343029 -5.179244  2.922615  4.691080 -4.420105  2.566498 -3.060573
1897   1.813780 -5.405847  3.592788 -3.851712 -7.006159  1.762055 -7.183935
1898  -0.113114  8.470661  1.234116  1.944084  3.719367  3.389321 -0.196834
1899   0.917953 -0.818779  0.940775 -5.312455  0.172059  0.153649 -1.344155

           PC8       PC9      PC10  ...      PC42      PC43      PC44  \
0    -0.804355 -2.147554 -1.428270  ... -0.461386 -0.119173  0.964281
1    -0.442742 -2.255078  5.917850  ...  2.546363 -1.527783  0.218121
2     0.750331 -1.350882  2.184040  ...  0.114919 -1.179193  0.383418
3     7.800037  3.625817 -0.480374  ... -1.616695 -1.701595  1.615355
4     0.737156 -5.000313  0.286066  ...  0.900311  0.902007 -0.422745
...        ...       ...       ...  ...       ...       ...       ...
1895  5.295553  4.362816 -5.501598  ...  1.751564  0.651270 -0.643220
1896 -0.833648  1.351051 -0.609913  ...  0.428818 -0.408585 -1.335426
1897 -0.517456 -6.721350  6.663945  ...  0.667027 -0.155089 -0.729783
1898  6.029436  2.850438 -0.909737  ... -1.295825 -0.930029  1.502968
1899 -0.026556 -0.703054  0.447665  ...  1.427105  0.690128  0.636673

          PC45      PC46      PC47      PC48      PC49      PC50  \
0     0.068468  1.017348  0.684371 -1.219599  0.464189 -0.330790
1    -0.585889  1.682326  0.909406  0.990845 -1.879798  1.857424
2    -0.845574  1.658271 -0.029213  1.037397  1.941564  1.085404
3    -0.712223  1.490877  0.366765  0.679153  0.389534 -0.283081
4     0.762301  1.484181 -1.550636  0.731239 -0.457406 -0.085305
...        ...       ...       ...       ...       ...       ...
1895  0.106702 -0.577589 -0.047206 -0.716166 -0.818295 -0.325957
1896  1.254881  0.659060 -1.499897  0.881856  2.079110  0.529715
1897  1.676116  0.092743 -0.956232  0.070251  0.929823 -0.499341
1898  0.975834  1.681756 -0.953862  0.127183  0.192006  0.030475
1899 -0.597274 -1.004919 -0.242898 -1.195132 -0.135985  1.225281

      experimental_proprty
0                     3.54
1                    -1.18
2                     3.69
3                     3.37
4                     3.10
...                    ...
1895                  2.06
1896                  3.03
1897                  3.80
1898                  3.22
1899                  1.75

[1900 rows x 51 columns]
Explained variance by each component: [0.36187679 0.09187459 0.05496059 0.03809547 0.0309894  0.02966831
 0.02600316 0.02119216 0.02034819 0.0199028  0.01698644 0.01388246
 0.01370506 0.01191935 0.01121417 0.01003138 0.00985007 0.00911795
 0.00863426 0.00797048 0.0072805  0.00718336 0.00707568 0.00644271
 0.00607228 0.00591211 0.00585807 0.00567904 0.00510106 0.00485315
 0.00465183 0.00443562 0.00421906 0.00391942 0.00381911 0.00375781
 0.00356525 0.00330305 0.00328775 0.00308139 0.0030196  0.00280756
 0.00274241 0.00259683 0.00247601 0.00245773 0.00236784 0.00226161
 0.00215134 0.00209936]

In [8]:
pca_components = pd.DataFrame(pca.components_, columns=cleaned_X.columns, index=[f'PC{i+1}' for i in range(pca.n_components_)])
pca_components

,nHetero,nX,C2SP3,MPC5,ATS0i,NaasN,SsCH3,nCl,nFAHRing,SlogP_VSA6,...,AATS0Z,ATSC0are,ATSC2pe,SsCl,ATS6v,AATSC1dv,nFARing,AATS2v,Xp-7dv,n6Ring
PC1,0.050516,0.015669,0.032960,0.062372,0.067988,0.015372,0.029202,0.006034,0.004144,0.022759,...,-0.009703,0.048124,0.018820,0.006600,0.068088,0.016812,0.005932,-0.021841,0.052932,0.041486
PC2,0.053908,0.051297,-0.073346,0.029680,-0.034940,0.056377,-0.021819,0.019110,-0.010239,0.024802,...,0.069150,0.030800,0.035256,0.018846,-0.008844,0.005476,-0.022096,0.103241,-0.022973,-0.012908
PC3,0.074624,0.096297,0.019973,-0.051262,0.005875,-0.030225,0.014280,0.015349,-0.010865,-0.071238,...,0.053665,0.097749,0.111945,0.013966,-0.010041,-0.033230,-0.011568,-0.029957,-0.003656,-0.068446
PC4,-0.029565,0.022534,-0.027282,-0.014979,-0.005905,-0.083233,-0.072986,0.073227,-0.009217,0.127379,...,0.072840,-0.020040,-0.019227,0.072375,-0.001138,-0.135595,-0.007010,0.092420,0.012128,0.060123
PC5,-0.059366,-0.045319,0.073061,0.032237,-0.022067,0.036158,0.009824,0.003926,0.026100,-0.031299,...,0.045153,-0.058587,0.030637,0.003636,0.016567,-0.051224,0.063650,0.050111,0.112923,-0.040562
PC6,0.050549,-0.008548,0.003780,-0.003488,-0.003495,-0.001849,-0.021578,0.076337,0.026036,-0.078654,...,0.103091,-0.049621,-0.064615,0.076298,-0.025263,-0.029006,0.017241,-0.015840,0.048115,-0.008255
PC7,0.015189,-0.018086,0.015872,-0.041381,0.012794,0.002358,0.000405,0.038347,-0.064347,0.032807,...,0.060704,-0.028463,-0.026540,0.038078,0.016793,-0.052515,-0.078593,-0.010935,-0.042045,-0.050706
PC8,0.037875,-0.027985,0.067340,-0.014716,0.015982,-0.032183,-0.052346,0.029818,-0.003895,-0.055240,...,0.021398,-0.000583,-0.063322,0.029512,-0.000683,-0.009351,-0.011466,0.001068,-0.023542,-0.064630
PC9,-0.005284,0.080654,0.077734,0.052429,-0.014815,-0.045990,-0.147496,0.063677,0.091046,-0.063496,...,0.011704,0.026683,-0.047027,0.063643,-0.019095,-0.053114,0.133600,0.048114,0.042364,0.105300
PC10,-0.009097,-0.025497,-0.033594,0.013952,-0.004738,-0.022853,0.105603,0.080000,0.032200,-0.069961,...,0.080546,-0.028253,-0.095281,0.080357,0.022383,0.077853,0.026796,-0.014684,-0.019296,0.023943
PC11,0.020704,-0.122812,-0.022559,0.002600,-0.008131,-0.022330,0.059575,-0.050111,0.035495,-0.017155,...,-0.080447,-0.005578,-0.052783,-0.051002,-0.001261,-0.039252,0.031352,0.009004,-0.007126,-0.040470
PC12,0.029742,-0.086125,0.043437,-0.001327,-0.001480,-0.023506,-0.111761,-0.055934,0.051702,-0.000338,...,-0.024943,-0.007907,-0.039715,-0.056506,-0.002782,-0.089481,0.022116,-0.021113,0.017005,0.046683
PC13,-0.003697,0.114042,-0.008856,-0.003347,0.000239,0.000583,-0.033191,0.092379,-0.017262,-0.019431,...,-0.012899,0.039819,0.014783,0.092250,0.003716,-0.011424,-0.045538,-0.031688,0.024564,-0.033311
PC14,-0.009813,0.030328,0.012099,0.002133,-0.014068,0.070338,-0.019931,0.122404,0.054861,0.018802,...,-0.022982,-0.033178,-0.027007,0.122489,0.039541,0.040783,0.027854,0.021589,-0.022146,-0.065206
PC15,-0.007347,0.001774,-0.032768,0.008025,-0.000855,0.034319,-0.033302,-0.067797,0.004461,0.007614,...,0.049623,0.034004,-0.001603,-0.068751,0.006212,-0.049116,-0.022254,0.011755,0.004081,0.010569
PC16,-0.020519,-0.011845,0.018133,0.004596,0.006788,-0.090503,0.010937,-0.116585,0.058070,0.003263,...,0.078436,-0.021740,0.023832,-0.116902,0.022523,0.026651,0.048682,0.018493,0.002404,0.005983
PC17,0.019623,0.017806,0.016021,0.003974,-0.002935,0.060342,0.013113,0.114005,-0.055455,-0.023971,...,-0.012184,-0.042338,0.034828,0.114335,-0.030506,0.023506,-0.016183,-0.003365,0.014364,0.053909
PC18,0.017746,-0.010275,-0.037173,0.003696,-0.001547,-0.112485,-0.019450,-0.026833,0.096072,-0.009500,...,-0.076023,0.010842,-0.016516,-0.027031,-0.013702,-0.015224,0.087063,0.011295,0.026081,-0.003854
PC19,0.020140,0.049568,-0.003632,-0.001856,-0.004299,-0.014460,-0.018428,0.136782,-0.104575,-0.013410,...,-0.046000,-0.036969,-0.005178,0.135095,0.040631,-0.065628,-0.128719,0.012774,0.003500,0.019613
PC20,-0.026616,0.021670,0.032978,-0.017112,0.002681,0.000984,0.041083,-0.058204,-0.004986,-0.054583,...,0.029196,0.023951,0.023575,-0.058586,0.000725,0.049771,-0.026193,-0.021244,-0.010296,-0.023931
PC21,0.014549,0.039226,-0.028413,0.006634,-0.001252,0.033237,0.003005,0.073426,-0.060860,-0.027833,...,-0.058557,-0.006722,0.025315,0.074495,-0.003472,-0.013637,-0.039625,0.014150,0.013547,0.015419
PC22,-0.018655,0.089479,0.078748,-0.006719,0.001109,0.019969,0.004506,0.068328,-0.026431,-0.010589,...,-0.012953,0.028907,0.010562,0.068995,0.021675,0.025208,-0.012879,-0.025198,0.015697,-0.030798
PC23,0.001975,-0.005386,0.038324,-0.010231,-0.000680,-0.014646,0.009497,0.004656,0.011020,0.011177,...,0.002600,-0.001996,-0.008552,0.005878,-0.023874,-0.003830,0.026088,-0.006713,0.027854,0.037473
PC24,-0.015746,0.033048,0.034830,-0.007045,-0.005853,-0.005458,-0.013173,-0.014826,0.053088,0.002960,...,0.013254,0.029369,0.043816,-0.015672,-0.013153,0.074728,0.001081,-0.020226,-0.003161,0.009153
PC25,-0.007971,-0.021098,0.018607,0.003342,0.004925,-0.011277,0.056765,-0.006438,-0.125178,-0.005385,...,0.023482,-0.014873,-0.045657,-0.007595,-0.000969,-0.017054,-0.099262,0.009261,-0.017833,-0.002869
PC26,-0.012377,0.009282,-0.017543,0.012824,-0.010159,0.036343,-0.020653,-0.019113,0.121394,0.038983,...,0.037404,-0.007185,0.020166,-0.019506,0.000509,-0.002896,0.072852,-0.051585,-0.023113,-0.039131
PC27,-0.004115,0.015494,0.076547,-0.004240,-0.002389,-0.005835,-0.008348,-0.059677,-0.103931,-0.030871,...,0.011676,0.020890,-0.007952,-0.060180,0.014551,0.039094,-0.073152,-0.010662,0.040357,-0.021384
PC28,0.000813,0.020416,0.023330,0.028879,-0.001739,-0.038426,0.001446,0.016268,0.072477,0.007551,...,-0.007575,0.000423,0.042892,0.016194,-0.001400,0.012259,0.086828,-0.046348,0.015897,0.025764
PC29,-0.002378,0.024759,0.020893,-0.003971,0.003407,-0.008171,0.030794,0.042681,-0.017770,0.018052,...,0.016680,-0.008154,-0.025305,0.043141,-0.003484,-0.046861,-0.019859,-0.003793,-0.026787,-0.086641
PC30,0.011692,0.004945,-0.076126,-0.003318,-0.003174,-0.002144,0.051696,-0.000663,0.008746,0.041292,...,-0.036210,-0.009122,-0.041573,-0.001256,0.016813,-0.074316,-0.022343,0.033505,0.017149,-0.039320
PC31,-0.008800,-0.027259,-0.063595,-0.007010,-0.003373,-0.126802,0.035830,-0.039177,-0.107973,-0.011785,...,0.021399,-0.013378,-0.033559,-0.038785,-0.020209,0.014126,-0.044723,-0.011625,-0.000121,0.010133
PC32,0.002419,0.028567,-0.002082,-0.021656,0.006344,-0.060755,0.057446,0.089673,0.143926,-0.000824,...,-0.022577,-0.016466,0.042038,0.088490,-0.007205,-0.000675,0.106122,0.013003,-0.019646,-0.024497
PC33,-0.015196,0.015345,-0.017619,0.019257,-0.004682,-0.117851,0.039723,-0.017705,0.072094,-0.026435,...,-0.023475,-0.003905,-0.074727,-0.019033,0.033757,-0.037971,0.076973,-0.012208,0.028985,0.013797
PC34,0.021004,-0.025950,0.022214,0.014691,-0.004070,0.002476,0.031251,0.005973,0.158994,-0.034945,...,0.001997,-0.017901,0.096473,0.006178,-0.002776,0.068125,0.153339,0.014883,-0.005599,0.006727
PC35,0.000408,-0.022746,-0.042594,0.042111,-0.011833,0.181720,-0.033250,-0.060349,0.124134,0.066107,...,0.011261,-0.010087,-0.027907,-0.059075,0.029186,-0.061828,0.124447,-0.009742,0.049027,0.059287
PC36,-0.008055,0.013151,0.012007,-0.002047,-0.013247,-0.132265,-0.001232,0.013967,0.090094,0.012361,...,-0.000691,-0.001038,0.057426,0.015858,0.013631,0.018047,0.046432,0.041138,-0.027721,0.010200
PC37,0.009044,-0.013383,0.001063,-0.017629,0.006972,-0.042060,0.048785,0.015863,0.057734,0.002185,...,-0.005780,-0.001530,0.095803,0.015318,0.004523,0.004041,0.075306,0.031040,-0.007346,0.007455
PC38,-0.007536,0.038548,-0.036634,0.022007,-0.001977,0.039659,0.039295,0.046609,0.124245,0.016379,...,0.015017,0.001194,0.016954,0.046769,-0.008162,0.000182,0.111385,0.018111,-0.015102,0.039071
PC39,0.025909,-0.008142,-0.073372,0.037394,-0.013279,0.071778,-0.051629,0.062383,-0.033006,-0.038968,...,0.007540,0.005958,0.041982,0.063061,-0.020238,0.036817,0.002996,-0.052137,-0.000097,-0.021615
PC40,0.005331,0.025186,-0.080797,0.012095,-0.011639,-0.033950,-0.061671,0.002986,-0.045253,0.013838,...,0.001296,0.025260,-0.049460,0.004073,0.001973,0.036428,-0.025206,-0.026423,-0.002980,0.035177
PC41,0.005118,-0.049859,-0.026419,-0.006270,0.007815,0.016164,-0.031857,-0.061868,-0.089563,0.029624,...,0.014890,-0.021309,0.050626,-0.063283,-0.008896,0.000491,-0.099192,0.019493,-0.017417,0.009883
PC42,0.019973,0.009557,-0.006099,0.011789,-0.006387,-0.077628,0.007955,-0.011130,0.006104,-0.045769,...,-0.014426,0.000437,-0.027136,-0.011271,-0.003644,0.039550,0.045470,0.003313,0.058966,0.013621
PC43,0.000421,-0.011835,-0.059353,-0.013042,0.010840,-0.012724,0.083623,-0.014236,0.007202,0.030884,...,-0.009402,0.008133,-0.052650,-0.014718,-0.017050,0.132273,0.024324,-0.008543,-0.002127,-0.005852
PC44,-0.000195,-0.003330,0.073534,-0.014467,0.006513,0.058503,-0.040112,0.015824,0.154295,-0.001480,...,-0.002650,-0.018574,-0.025920,0.015179,-0.007758,-0.009634,0.135248,-0.021675,-0.003519,-0.032267
PC45,0.016947,0.015538,-0.004237,0.010235,-0.012373,0.105424,-0.038328,-0.035782,-0.076976,0.050771,...,-0.031850,0.004806,0.012160,-0.035587,-0.008195,-0.013717,-0.032852,-0.030998,0.052438,0.009419
PC46,0.004971,0.034202,-0.026435,-0.014586,-0.007270,0.053005,0.018913,-0.025521,0.098332,-0.009473,...,0.009153,0.022988,-0.065640,-0.026722,-0.007295,-0.005690,0.074949,-0.001331,-0.047591,-0.006623
PC47,0.015249,-0.004919,-0.013343,0.001267,0.000661,0.067994,0.057918,0.008112,0.030916,0.012929,...,0.011600,-0.004322,0.032437,0.006198,-0.019868,0.001179,0.012356,-0.007421,-0.011726,-0.009381
PC48,-0.008542,-0.024936,-0.025886,0.014336,-0.011483,-0.156054,-0.015849,-0.036524,-0.028184,0.015257,...,-0.002372,-0.008321,0.020277,-0.035722,0.014608,-0.032137,0.007103,0.014406,0.036898,0.021739
PC49,-0.017031,0.056681,-0.020457,-0.002235,-0.007772,-0.053888,-0.001081,0.020402,0.045745,-0.017959,...,-0.013072,0.008755,-0.049593,0.020552,-0.006742,0.030252,0.036804,0.003449,-0.057928,-0.046436
PC50,0.009563,0.011804,-0.029241,0.007925,-0.002295,-0.027250,0.010010,-0.015975,0.115618,-0.009367,...,-0.005108,0.003264,-0.009928,-0.013714,-0.015383,0.038011,0.100266,-0.007400,-0.021334,-0.030646

In [9]:
for i in range(1,PCA_COMPONENTS + 1):
    top_features_pcx = pca_components.loc[f'PC{i}'].abs().sort_values(ascending=False)
    print(top_features_pcx.index[0])

ATS0d
AATS2dv
EState_VSA1
C2SP2
Xpc-6dv
MIC0
ATSC3d
nHBDon
nARing
ATSC2v
nO
AATSC3v
ATSC3v
ATSC1are
ATSC8pe
VSA_EState4
PEOE_VSA2
NaaS
SsNH2
NtsC
ATSC4are
ATSC8se
ATSC3pe
Diameter
NsOH
ATSC7i
ATSC7pe
ATSC5se
ATSC8p
NdsCH
ATSC7se
SssNH
SaaNH
SssS
SaasN
NaaNH
SdsCH
SdsCH
C3SP2
SdsCH
NdsCH
SssS
SaaO
EState_VSA5
SsBr
ATSC6i
SdNH
SaaO
AATSC0v
StCH

## Use tSNE or UMAP - used for big data dont run on laptop if data points are 10k*10k for bonus ques